cltool/cl/urls.py
from django.urls import path

from . import views

app_name = 'cl'
urlpatterns = [
    path('', views.index, name='index'),
    path('results/', views.results, name='results'),
]

cltool/cltool/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('cl.urls')),
    path('admin/', admin.site.urls),
]

cltool/cl/models.py
from django.db import models
from decimal import Decimal

import datetime
# Create your models here.
class ContactLens(models.Model):
    clens = models.CharField(max_length=128)
    num_year_supply = models.IntegerField()
    cost_per_package = models.DecimalField(max_digits=7, decimal_places=2)
    def __str__(self):
        return self.clens
    def has_rebate(self):
        cur_dt = datetime.date.today()
        rebates = self.contactrebate_set.exclude(to_dt__lt=cur_dt).exclude(from_dt__gt=cur_dt)
        if len(rebates):
            return "rebate"
        else:
            return ""
    class Meta:
        ordering = ["clens"]
        verbose_name_plural = "Contact lenses"


class ContactAttribute(models.Model):
    attribute = models.CharField(max_length=64)
    clenses = models.ManyToManyField(ContactLens)
    def __str__(self):
        return self.attribute
    class Meta:
        ordering = ["attribute"]

class ContactRebate(models.Model):
    desc = models.CharField(max_length=64)
    from_dt = models.DateField()
    to_dt = models.DateField()
    lenses = models.ManyToManyField(ContactLens)
    exclusive = models.BooleanField(default=True)
    amt = models.DecimalField(max_digits=7, decimal_places=2)
    half_amt = models.DecimalField(default=0, max_digits=7, decimal_places=2)
    def __str__(self):
        return self.desc + ': ' + str(self.amt)
    class Meta:
        ordering = ["-to_dt"]

class ConfigDefaults(models.Model):
    def_cl_service_amt = models.DecimalField(max_digits=7, decimal_places=2)
    def_exam_amt = models.DecimalField(max_digits=7, decimal_places=2)
    def_benefit_amt = models.DecimalField(max_digits=7, decimal_places=2)
    def_ys_discount = models.DecimalField(max_digits=3, decimal_places=1)
    class Meta:
        verbose_name_plural="Defaults (only 1 record)"

cltool/cl/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse

import datetime

from decimal import Decimal, getcontext
from .models import ContactLens, ConfigDefaults

# Create your views here.
def index(request):
    cl_list = ContactLens.objects.order_by('clens')
    for cl in cl_list:
        cl.ys = cl.cost_per_package * cl.num_year_supply * 2
    def_amts = ConfigDefaults.objects.get(pk=1)
    cur_dt = datetime.date.today().strftime('%Y-%m-%d')
    print(cur_dt)
    context = {
        'cl_list': cl_list,
        'def_amts': def_amts,
        'cur_dt': cur_dt,
    }
    return render(request, 'cl/index.html', context)

def results(request):
    def_amts = ConfigDefaults.objects.get(pk=1)
    TP = Decimal(10) ** -2
    exam_dt = datetime.datetime.strptime(request.POST['exam_dt'], "%Y-%m-%d").date()
    od_cl = request.POST['od_cl']
    od_contactlens = ContactLens.objects.get(pk=od_cl)
    od_contactlens.ys = (od_contactlens.cost_per_package * ((Decimal(100.0) - def_amts.def_ys_discount) / Decimal(100.0))).quantize(TP)
    od_rebates = od_contactlens.contactrebate_set.exclude(to_dt__lt=exam_dt).exclude(from_dt__gt=exam_dt)
    od_yearsupply = (od_contactlens.num_year_supply * od_contactlens.cost_per_package).quantize(TP)
    od_6month_supply = (od_yearsupply / Decimal(2)).quantize(TP)
    os_cl = request.POST['os_cl']
    os_contactlens = ContactLens.objects.get(pk=os_cl)
    os_contactlens.ys = (os_contactlens.cost_per_package * ((Decimal(100.0) - def_amts.def_ys_discount) / Decimal(100.0))).quantize(TP)
    os_rebates = os_contactlens.contactrebate_set.exclude(to_dt__lt=exam_dt).exclude(from_dt__gt=exam_dt)
    os_yearsupply = (os_contactlens.num_year_supply * os_contactlens.cost_per_package).quantize(TP)
    os_6month_supply = (os_yearsupply / Decimal(2)).quantize(TP)
    year_supply = (od_yearsupply + os_yearsupply).quantize(TP)
    year_discount = (year_supply * (def_amts.def_ys_discount / Decimal(100.0))).quantize(TP)
    halfyear_supply = (od_6month_supply + os_6month_supply).quantize(TP)
    halfyear_discount = (Decimal("0.00")).quantize(TP)
    discounted_year_supply = (year_supply - year_discount).quantize(TP)
    cl_service_amt = (Decimal(request.POST['cl_service_amt'])).quantize(TP)
    exam_amt = (Decimal(request.POST['exam_amt'])).quantize(TP)
    benefit_amt = (Decimal(request.POST['benefit_amt'])).quantize(TP)
    total_year = (discounted_year_supply + cl_service_amt + exam_amt - benefit_amt).quantize(TP)
    total_halfyear = (halfyear_supply + cl_service_amt + exam_amt - benefit_amt).quantize(TP)
    rebates = []
    amt = Decimal(0)
    num_exclusive=0
    num_nonexclusive=0
    od_ne = Decimal(0)
    os_ne = Decimal(0)
    dtot_ne = Decimal(0)
    tot_year_ne = Decimal(0)
    num_rebates = 0
    if len(od_rebates) == len(os_rebates) and len(od_rebates) > 0:
        for i in range(0,len(od_rebates)):
            num_rebates += 1
            rebates.append({
                'amt': (od_rebates[i].amt + os_rebates[i].amt).quantize(TP),
                'dtot': (discounted_year_supply - od_rebates[i].amt - os_rebates[i].amt).quantize(TP),
                'gtot': (total_year - od_rebates[i].amt - os_rebates[i].amt).quantize(TP),
            })
            if od_rebates[i].exclusive:
                num_exclusive += 1
            else:
                num_nonexclusive += 1
                od_ne += od_rebates[i].amt
                os_ne += os_rebates[i].amt
                amt += od_rebates[i].amt + os_rebates[i].amt
# Kludge!!!!!  Want to get total for non-exclusive Rebates added together
#        if num_exclusive == 0:
#            rebates[0]['amt'] = (amt).quantize(TP)
#            rebates[0]['dtot'] = (discounted_year_supply - amt).quantize(TP)
#            rebates[0]['gtot'] = (total_year - amt).quantize(TP)
    if num_nonexclusive > 1:
        num_rebates += 1
        od_ne = (od_ne).quantize(TP)
        os_ne = (os_ne).quantize(TP)
        amt = (amt).quantize(TP)
        dtot_ne = (discounted_year_supply - amt).quantize(TP)
        tot_year_ne = (total_year - amt).quantize(TP)
    else:
        od_ne = 0
        os_ne = 0
        amt = 0
        dtot_ne = 0
        tot_year_ne = 0
    context = {
        'exam_dt': exam_dt.strftime("%m/%d/%Y"),
        'od_contactlens': od_contactlens,
        'od_yearsupply': od_yearsupply,
        'od_6month_supply': od_6month_supply,
        'os_contactlens': os_contactlens,
        'os_yearsupply': os_yearsupply,
        'os_6month_supply': os_6month_supply,
        'year_supply': year_supply,
        'year_discount': year_discount,
        'discounted_year_supply': discounted_year_supply,
        'halfyear_supply': halfyear_supply,
        'halfyear_discount': halfyear_discount,
        'cl_service_amt': cl_service_amt,
        'exam_amt': exam_amt,
        'benefit_amt': benefit_amt,
        'total_year': total_year,
        'total_halfyear': total_halfyear,
        'od_rebates': od_rebates,
        'os_rebates': os_rebates,
        'rebates': rebates,
        'amt': amt,
        'od_ne': od_ne,
        'os_ne': os_ne,
        'dtot_ne': dtot_ne,
        'tot_year_ne': tot_year_ne,
        'num_rebates': (num_rebates * 2),
    }
    return render(request, 'cl/results.html', context)

cltool/cl/templates/cl/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <title>Contact Tool</title>
  </head>
  <body>
    <div class="container">
      <div class="jumbotron">
        <a href="{% url 'admin:index' %}"><img class="rounded float-right" src="{% static 'lol-logo.png' %}" alt="Logo"></a>
        <h1>Savings Calculator</h1>
        <p>Quickly calculate the savings on annual contact lens supply.</p>
      </div>
      {% block content %}
      {% endblock %}
    </div>
    <script src="{% static 'jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'popper.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    {% block script %}
    {% endblock %}
  </body>
</html>

cltool/cl/templates/cl/index.html
{% extends 'cl/base.html'%}
{% block content %}
  {% if cl_list %}
  <form action="{% url 'cl:results' %}" method="post">
    {% csrf_token %}
    <div class="row">
      <div class="col-7">
        <input class="form-control" id="clSearch" type="text" placeholder="Search for lenses.." autofocus>
          <table class="table table-hover table-sm table-bordered">
            <thead>
              <tr>
                <th>Contact Lens</th>
                <th class="text-center">Right Eye</th>
                <th class="text-center">Left Eye</th>
              </tr>
            </thead>
            <tbody id="Choices">
              {% for cl in cl_list %}
              <tr>
                <td>
                  <div
                    class="form-check-label"
                    href="#" data-html="true"
                    data-toggle="popover"
                    data-trigger="hover"
                    data-placement="bottom"
                    title="{{ cl.clens }}"
                    data-content="
                      <ul class=list-group>
                        <li class=list-group-item>${{ cl.cost_per_package }} per package.</li>
                        <li class=list-group-item>{{ cl.num_year_supply }} pack(s) per eye for a year supply.</li>
                        <li class=list-group-item>${{ cl.ys }} year supply for both eyes.</li>
                      </ul>
                    "
                  >{{ cl.clens }}</div>
                  <div style="display:none;">{% if cl.has_rebate %}{{ cl.has_rebate }} {% endif %}{% for a in cl.contactattribute_set.all %}{{ a.attribute }} {% endfor %}
                  </div>
                </td>
                <td class="text-center"><input class="custom-radio" type="radio" name="od_cl" value="{{ cl.id }}" required></td>
                <td class="text-center"><input class="custom-radio" type="radio" name="os_cl" value="{{ cl.id }}" required></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
      </div>
      <div class="col-5">
        <div class="form-group">
          <label for="cl_service_amt">Contact Lens Eval/Service:</label>
          <input class="form-control" type="number" name="cl_service_amt" value="{{ def_amts.def_cl_service_amt }}" step="0.01" required>
        </div>
        <div class="form-group">
          <label for="exam_amt">Exam Amount (or benefit copay):</label>
          <input class="form-control" type="number" name="exam_amt" value="{{ def_amts.def_exam_amt }}" step="0.01" required>
        </div>
        <div class="form-group">
          <label for="benefit_amt">3rd Party Benefit Amount:</label>
          <input class="form-control" type="number" name="benefit_amt" value="{{ def_amts.def_benefit_amt }}" step="0.01" required>
        </div>
        <div class="form-group">
          <label for="exam_dt">Date of Sale:</label>
          <input class="form-control" type="date" name="exam_dt" value="{{ cur_dt }}" required>
        </div>
        <button type="submit" class="btn btn-outline-primary" id="calculate">Calculate</button>
      </div>
    </div>
  </form>
  {% else %}
    <p>No cls in list</p>
  {% endif %}
{% endblock %}
{% block script %}
<script>
$(document).ready(function(){
  $('[data-toggle="popover"]').popover();
  $('#clSearch').on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $('#Choices tr').filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
{% endblock %}

cltool/cl/templates/cl/results.html
{% extends 'cl/base.html' %}
{% block content %}
<table class="table table-responsive table-sm">
  <tr>
    <th></th>
    <th>Contact Lens</th>
    <th>Year Supply</th>
    <th>6-Month Supply</th>
    {% if rebates %}
      <th colspan="{{ num_rebates }}" class="text-center">Sale Date: {{ exam_dt }} / Active Rebates</th>
    {% else %}
      <th class="text-center">Sale Date: {{ exam_dt }} / <b>NO</b> active Rebates</th>
    {% endif %}
  </tr>
  <tr>
    <td>Right Eye</td>
    <td>
      <div
        class="form-check-label"
        href="#" data-html="true"
        data-toggle="popover"
        data-trigger="hover"
        data-placement="right"
        title="{{ od_contactlens.clens }}"
        data-content="
          <ul class=list-group>
            <li class=list-group-item>${{ od_contactlens.cost_per_package }} per package.</li>
            <li class=list-group-item>{{ od_contactlens.num_year_supply }} pack(s) per eye for a year supply.</li>
            <li class=list-group-item>${{ od_contactlens.ys }} discounted cost per package.</li>
          </ul>
        "
        >{{ od_contactlens.clens }}
      </div>
    </td>
    <td>{{ od_yearsupply }}</td>
    <td>{{ od_6month_supply }}</td>
    {% for r in od_rebates %}
      <td>{{ r.desc }}</td>
      <td>{{ r.amt }}</td>
    {% endfor %}
    {% if od_ne %}
      <td>Total NE Rebates:</td>
      <td>{{ od_ne }}</td>
    {% endif %}
  </tr>
  <tr>
    <td>Left Eye</td>
    <td>
      <div
        class="form-check-label"
        href="#" data-html="true"
        data-toggle="popover"
        data-trigger="hover"
        data-placement="right"
        title="{{ os_contactlens.clens }}"
        data-content="
          <ul class=list-group>
            <li class=list-group-item>${{ os_contactlens.cost_per_package }} per package.</li>
            <li class=list-group-item>{{ os_contactlens.num_year_supply }} pack(s) per eye for a year supply.</li>
            <li class=list-group-item>${{ os_contactlens.ys }} discounted cost per package.</li>
          </ul>
        "
        >{{ os_contactlens.clens }}
      </div>
    </td>
    <td>{{ os_yearsupply }}</td>
    <td>{{ os_6month_supply }}</td>
    {% for r in os_rebates %}
      <td>{{ r.desc }}</td>
      <td>{{ r.amt }}</td>
    {% endfor %}
    {% if os_ne %}
      <td>Total NE Rebates:</td>
      <td>{{ os_ne }}</td>
    {% endif %}
  </tr>
  <tr>
    <td class="table-secondary"></td>
    <td class="table-secondary">Total:</td>
    <td class="table-secondary">{{ year_supply }}</td>
    <td class="table-secondary">{{ halfyear_supply }}</td>
    {% for r in rebates %}
      <td class="table-secondary"></td>
      <td class="table-warning">{{ r.amt }}</td>
    {% endfor %}
    {% if amt %}
      <td class="table-secondary"></td>
      <td class="table-warning">{{ amt }}</td>
    {% endif %}
  </tr>
  <tr>
    <td></td>
    <td class="table-warning">(-) Discount for Year Supply</td>
    <td class="table-warning">{{ year_discount }}</td>
    <td>{{ halfyear_discount }}</td>
  </tr>
  <tr class="table-secondary">
    <td></td>
    <td>(=) Discounted Total</td>
    <td>{{ discounted_year_supply }}</td>
    <td>{{ halfyear_supply }}</td>
    {% for r in rebates %}
      <td></td>
      <td>{{ r.dtot }}</td>
    {% endfor %}
    {% if amt %}
      <td></td>
      <td>{{ dtot_ne }}</td>
    {% endif %}
  </tr>
  <tr>
    <td></td>
    <td>(+) Contact Lens Evaluation</td>
    <td colspan="2" class="text-center">{{ cl_service_amt }}</td>
  </tr>
  <tr>
    <td></td>
    <td>(+) Examination (or Benefit Copay)</td>
    <td colspan="2" class="text-center">{{ exam_amt }}</td>
  </tr>
  <tr>
    <td></td>
    <td>(-) 3rd Party Benefit Amount</td>
    <td colspan="2" class="text-center">{{ benefit_amt }}</td>
  </tr>
  <tr class="table-success">
    <td></td>
    <td>(=) Grand Total:</td>
    <td>{{ total_year }}</td>
    <td>{{ total_halfyear }}</td>
    {% for r in rebates %}
      <td></td>
      <td>{{ r.gtot }}</td>
    {% endfor %}
    {% if amt %}
      <td></td>
      <td>{{ tot_year_ne }}</td>
    {% endif %}
  </tr>
</table>
  <a href="{% url 'cl:index' %}" id="again" class="btn btn-outline-primary" autofocus>Calculate another</a>
{% endblock %}
{% block script %}
<script>
$("#again").focus();
$(document).ready(function(){
  $('[data-toggle="popover"]').popover();
});
</script>
{% endblock %}